### ISSUE TITLE
Connection Refused Error when Running Docker Compose for amarr

### ISSUE THREAD

**Issue by Alexandrump** [vexdev/amarr#46]
Hello,
I am encountering an issue while trying to run the amarr Docker container using the provided Docker Compose configuration.
 I would appreciate your help in resolving this problem. Below are the technical details:

**Issue Description:**
When attempting to run the amarr Docker container, I am getting a "Connection Refused" error, as shown in the error log. This error prevents the amarr application from starting properly.

**Error Log:**
```
2023-11-09 19:23:32.360 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
Exception in thread "main" java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        ...
        at amarr.AppKt.main(App.kt)
```

**Docker Compose Configuration:**
```yaml
services:

  amarr:
    image: vexdev/amarr:latest
    environment:
      - AMULE_HOST=amarr
      - AMULE_PORT=4712
      - AMULE_PASSWORD=secret
      - AMARR_LOG_LEVEL=ERROR
      - AMULE_FINISHED_PATH=/downloads
    volumes:
      - /home/server/.config/appdata/amarr/config:/config
    ports:
      - 8080:8084
```

**Environment Details:**
- Operating System: Ubuntu 22.04
- Docker Version: Docker version 24.0.7, build afdd53b
- Docker Compose Version: Docker Compose version v2.21.0

**Expected Behavior:**
The amarr container should start without any connection issues, and the application should run successfully.

**Additional Information:**
- The amule service seems to be specified with `AMULE_HOST=amarr`, but there might be an issue with this configuration, isn't it?. Please verify if it should be pointing to a different host or address.

I would greatly appreciate your assistance in resolving this issue, as I am looking forward to using the amarr application. If you require any additional information or logs, please let me know.

Thank you for your time and support.

**Complete Error Log:**
```
2023-11-09 19:23:32.360 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
Exception in thread "main" java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/java.net.Socket.connect(Socket.java:583)
        at java.base/java.net.Socket.<init>(Socket.java:507)
        at java.base/java.net.Socket.<init>(Socket.java:287)
        at jamule.AmuleConnection.<init>(AmuleConnection.kt:25)
        at jamule.AmuleClient.<init>(AmuleClient.kt:23)
        at jamule.AmuleClient.<init>(AmuleClient.kt:16)
        at amarr.AppKt.buildClient(App.kt:83)
        at amarr.AppKt.app(App.kt:49)
        at amarr.AppKt$main$1.invoke(App.kt:42)
        at amarr.AppKt$main$1.invoke(App.kt:39)
        at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:51)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:319)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
        at amarr.AppKt.main(App.kt:43)
        at amarr.AppKt.main(App.kt)
```

**Comment by vexdev** [comment]
Hey, I'll be off till end of month so cannot help much, but on first look
it looks like you're not pointing amarr to amule. You need to give amarr
the hostname of amule so it can connect to it. If amule is running on
docker this will be something like "amule" or else the name of the
container which runs amule, if it's running on the host (your computer
directly) then it may be something like 172.17.0.1

Luca

**Comment by Alexandrump** [comment]
Correct. I suggest that you explain in the documentation that it's mandatory to have installed amule or some container with it.

Thank you so much!

**Comment by Marcosaurios** [comment]
Yeah I also found it a bit difficult to understand that the `amule` docker image needed to be running from reading the docs. But giving a deeper read yuo'd be able to guess it :P

**Comment by isc30** [comment]
hey, the container crashes from time to time, ideally add `restart: unless-stopped` in the docker-compose.yml file and done 👯

**Comment by vexdev** [comment]
@isc30 It would be useful to have a log in case it crashes, please open a ticket in that case (It should not crash :) )
