### ISSUE TITLE
Host not reachable

### ISSUE THREAD

**Issue by vk496** [vexdev/amarr#70]
Hello and thank you for this great project!

Im trying to deploy amarr to TrueNAS as custom app (essentially, kubernetes under the hood) without success:
```java
2024-01-29 16:18:37.635 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
Exception in thread "main" java.net.UnknownHostException: amule-ec.ix-amule.svc.cluster.local
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at jamule.AmuleConnection$1.invoke(AmuleConnection.kt:32)
	at jamule.AmuleConnection$1.invoke(AmuleConnection.kt:32)
	at jamule.AmuleConnection.<init>(AmuleConnection.kt:24)
	at jamule.AmuleConnection.<init>(AmuleConnection.kt:32)
	at jamule.AmuleClient.<init>(AmuleClient.kt:23)
	at jamule.AmuleClient.<init>(AmuleClient.kt:16)
	at amarr.AppKt.buildClient(App.kt:83)
	at amarr.AppKt.app(App.kt:49)
	at amarr.AppKt$main$1.invoke(App.kt:42)
	at amarr.AppKt$main$1.invoke(App.kt:39)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:51)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:319)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
	at amarr.AppKt.main(App.kt:43)
	at amarr.AppKt.main(App.kt)
```

I was able to verify from another container that `amule-ec.ix-amule.svc.cluster.local` is reachable in port `4712`:
```
/ # nmap -p 4712 amule-ec.ix-amule.svc.cluster.local
Starting Nmap 7.94 ( https://nmap.org ) at 2024-01-29 16:28 UTC
Nmap scan report for amule-ec.ix-amule.svc.cluster.local (172.17.119.223)
Host is up (0.000067s latency).

PORT     STATE SERVICE
4712/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.20 seconds
```

Anybody have a guess of what is going on?

I previously deployed it without any problem on Docker. K8s should be exactly the same...

BR,
Valentin

**Comment by vk496** [comment]
nvm, found the issue:

![image](https://github.com/vexdev/amarr/assets/5502443/7911ea18-98bc-43f6-91ad-b3c25d854432)

I was missing proritize k8s dns
