### ISSUE TITLE
DOESN'T WORK

### ISSUE THREAD

**Issue by Sermatty** [vexdev/amarr#91]
Hi, I am a person who was looking at the issues on GitHub and I came across the same problem as in issue 76. I followed the entire discussion and I have the same version of Amar as the user in that issue. I also have the same configuration and I am using an internal IP. Now, I will share the Docker Compose configurations as well as the logs for Amar and Sonarr.

amarr log:

```
2024-07-21 10:36:43.615 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
2024-07-21 10:36:58.681 [main] INFO  ktor.application - Application started in 18.574 seconds.
2024-07-21 10:36:58.685 [main] DEBUG ktor.application - Application started: io.ktor.server.application.Application@4e31276e
2024-07-21 10:37:08.479 [DefaultDispatcher-worker-1] INFO  ktor.application - Responding at http://0.0.0.0:8080/

```

sonarr log:
```
2024-07-21 12:45:02.7|Error|QBittorrent|Unable to test qBittorrent

[v4.0.6.1805] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.
 ---> System.Net.WebException: Http request timed out
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 144
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157

   --- End of inner exception stack trace ---
2024-07-21 12:45:08.0|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to qBittorrent
 
```
 
 it seems like sonarr doesn't even connect to amarr.

amarr+amule docker-compose conf:

```
version: "2.1"

networks:
  internal:
    driver: bridge

services:
  amule:
    image: ngosang/amule
    container_name: amule
    environment:
      
PUID=1000
PGID=1000
TZ=Europe/London
GUI_PWD=admin
WEBUI_PWD=admin
MOD_AUTO_RESTART_ENABLED=true
MOD_AUTO_RESTART_CRON=0 6 * * *
MOD_AUTO_SHARE_ENABLED=false
MOD_AUTO_SHARE_DIRECTORIES=/incoming;/my_movies
MOD_FIX_KAD_GRAPH_ENABLED=true
MOD_FIX_KAD_BOOTSTRAP_ENABLED=true
ports:
"4711:4711" # web ui
"4712:4712" # remote gui, webserver, cmd ...
"4662:4662" # ed2k tcp
"4665:4665/udp" # ed2k global search udp (tcp port +3)
"4672:4672/udp" # ed2k udp
volumes:
/share/CACHEDEV1_DATA/Container/container-station-data/plex_auto/docker/amule:/home/amule/.aMule
/share/CACHEDEV2_DATA/downloads:/incoming
/share/CACHEDEV2_DATA/downloads/temp:/temp
restart: unless-stopped
amarr:
  image: vexdev/amarr:latest
  container_name: amarr
  environment:
AMULE_HOST=192.168.1.51
AMULE_PORT=4712
AMULE_PASSWORD=admin
AMARR_LOG_LEVEL=DEBUG
volumes:
/share/CACHEDEV1_DATA/Container/container-station-data/plex_auto/docker/amarr/config:/config
ports:
8082:8080
```

![amule](https://github.com/user-attachments/assets/112fd44c-42f2-47cb-af49-7b5f77b75c79)

**Comment by vexdev** [comment]
Resolved - due to some networking issue.
